"""empty message

Revision ID: 3220869566e7
Revises: 37ef14468bcf
Create Date: 2023-08-01 16:47:58.379180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3220869566e7'
down_revision = '37ef14468bcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('highscores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['username_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('highscores')
    # ### end Alembic commands ###
